/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBarDrawer: typeof import('./src/components/NavBarDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WifisetupPanel: typeof import('./src/components/WifisetupPanel.vue')['default']
  }
}
